//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingApp.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interview
    {
        public Interview()
        {
            this.InterviewQuestions = new HashSet<InterviewQuestion>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string user { get; set; }
    
        public virtual ICollection<InterviewQuestion> InterviewQuestions { get; set; }
    }
}
