//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingApp.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public int Id { get; set; }
        public string QuestionText { get; set; }
        public string ProjectName { get; set; }
        public string Revision { get; set; }
        public int TrainingCategoryId { get; set; }
    
        public virtual TrainingCategory TrainingCategory { get; set; }
    }
}
